---
title: Using Skimr for Initial EDA
author: David Timewell
date: '2020-08-16'
slug: index.en-us
categories:
  - R
tags:
  - EDA
thumbnailImage: "img/skim.jpg"
thumbnailImagePosition: left  

keywords:
  - tech
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<p>If you are using summary for your summary stastics,consider using skimr.
This post introduces skimr.</p>
<!--more-->
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>When beginning to use R one of the first things to do after getting a view of the dataset you are dealing using glimpse() and str()
is to start looking at basic descriptive statistics. In the past I used summary extensivly to do this.
I was going through a tutorial on EDA and linear regression and the author used the skimr package which I thought was a great alternative for quickly getting basic statistics.</p>
<p>Personally I prefer the structure of the skimr output and how it can be customised for your own needs.</p>
</div>
<div id="why-use-skimr" class="section level2">
<h2>Why use Skimr</h2>
<ul>
<li>It has a wider array of statistics than summary</li>
<li>Returns a skim_df object which can be used with dplyr pipeline’s and tidyverse functions</li>
<li>Includes a sparkline if wanted with either a bar or line.</li>
<li>Splits data types into separate sections</li>
<li>Allows creating your own statistics with skim_with()</li>
<li>Built in support for strings, lists and other column classes.</li>
</ul>
</div>
<div id="some-examples" class="section level2">
<h2>Some examples</h2>
<p>In the examples to follow I use different tidyverse verbs and different methods of displaying data.</p>
<div id="default-output" class="section level3">
<h3>Default output</h3>
<p>Below is the default output from the command when run on a dataset. I will use the mpg dataset.
Below the output is separated into a summary section and then split by variable types being character and numeric in this instance.
Note the inclusion of spark lines and some additional statistics not included in summary() function.</p>
<pre class="r"><code>library(tidyverse)
library(skimr)</code></pre>
<pre class="r"><code>skim(mpg)</code></pre>
<table>
<caption>(#tab:basic_out)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mpg</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">manufacturer</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">15</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">model</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">22</td>
<td align="right">0</td>
<td align="right">38</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">trans</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">8</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">10</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">drv</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">fl</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">class</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">displ</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3.47</td>
<td align="right">1.29</td>
<td align="right">1.6</td>
<td align="right">2.4</td>
<td align="right">3.3</td>
<td align="right">4.6</td>
<td align="right">7</td>
<td align="left">▇▆▆▃▁</td>
</tr>
<tr class="even">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2003.50</td>
<td align="right">4.51</td>
<td align="right">1999.0</td>
<td align="right">1999.0</td>
<td align="right">2003.5</td>
<td align="right">2008.0</td>
<td align="right">2008</td>
<td align="left">▇▁▁▁▇</td>
</tr>
<tr class="odd">
<td align="left">cyl</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.89</td>
<td align="right">1.61</td>
<td align="right">4.0</td>
<td align="right">4.0</td>
<td align="right">6.0</td>
<td align="right">8.0</td>
<td align="right">8</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="even">
<td align="left">cty</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">16.86</td>
<td align="right">4.26</td>
<td align="right">9.0</td>
<td align="right">14.0</td>
<td align="right">17.0</td>
<td align="right">19.0</td>
<td align="right">35</td>
<td align="left">▆▇▃▁▁</td>
</tr>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.44</td>
<td align="right">5.95</td>
<td align="right">12.0</td>
<td align="right">18.0</td>
<td align="right">24.0</td>
<td align="right">27.0</td>
<td align="right">44</td>
<td align="left">▅▅▇▁▁</td>
</tr>
</tbody>
</table>
</div>
<div id="what-did-we-return" class="section level3">
<h3>What did we return ?</h3>
<p>Because skim returns a skim_df object this is pipeable and open to additional manipulation.
Looking at the structure of the skim_df we can get an orientation of how it’s made up.
I use to_long in the below to get a look at skim_type, skim_variable and stat.</p>
<p>Looking at the below n_missing and complete_rate are base skimmers. The rest are type-base skimmers and we need
to use the skim_type prefix to refer to the correct column.</p>
<pre class="r"><code>to_long(skim(mpg,model,hwy)) %&gt;% select(skim_type,skim_variable,stat) %&gt;% arrange(skim_type)</code></pre>
<pre><code>## # A tibble: 17 x 3
##    skim_type skim_variable stat                
##    &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;               
##  1 character model         n_missing           
##  2 character model         complete_rate       
##  3 character model         character.min       
##  4 character model         character.max       
##  5 character model         character.empty     
##  6 character model         character.n_unique  
##  7 character model         character.whitespace
##  8 numeric   hwy           n_missing           
##  9 numeric   hwy           complete_rate       
## 10 numeric   hwy           numeric.mean        
## 11 numeric   hwy           numeric.sd          
## 12 numeric   hwy           numeric.p0          
## 13 numeric   hwy           numeric.p25         
## 14 numeric   hwy           numeric.p50         
## 15 numeric   hwy           numeric.p75         
## 16 numeric   hwy           numeric.p100        
## 17 numeric   hwy           numeric.hist</code></pre>
</div>
<div id="selecting-from-skim_df" class="section level3">
<h3>Selecting from skim_df</h3>
<p>Below an example of what I mean by selecting type based and base skimmers.
Note n_missing is our base skimmer and numeric.mean and character.n_unique are our type-based skimmers.</p>
<pre class="r"><code>skim(mpg) %&gt;% select(skim_type,skim_variable,n_missing,numeric.mean,character.n_unique)</code></pre>
<table>
<caption>(#tab:structure_selecting_the_df1)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mpg</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">manufacturer</td>
<td align="right">0</td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left">model</td>
<td align="right">0</td>
<td align="right">38</td>
</tr>
<tr class="odd">
<td align="left">trans</td>
<td align="right">0</td>
<td align="right">10</td>
</tr>
<tr class="even">
<td align="left">drv</td>
<td align="right">0</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="left">fl</td>
<td align="right">0</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="left">class</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">displ</td>
<td align="right">0</td>
<td align="right">3.47</td>
</tr>
<tr class="even">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">2003.50</td>
</tr>
<tr class="odd">
<td align="left">cyl</td>
<td align="right">0</td>
<td align="right">5.89</td>
</tr>
<tr class="even">
<td align="left">cty</td>
<td align="right">0</td>
<td align="right">16.86</td>
</tr>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">23.44</td>
</tr>
</tbody>
</table>
</div>
<div id="selecting-specific-columns-from-our-data" class="section level3">
<h3>Selecting specific columns from our data</h3>
<p>Only specific columns can be selected if desired. Note there are many ways to do this. We can also use pipe and select.</p>
<pre class="r"><code>skim(mpg,hwy)</code></pre>
<table>
<caption><span id="tab:select">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mpg</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.44</td>
<td align="right">5.95</td>
<td align="right">12</td>
<td align="right">18</td>
<td align="right">24</td>
<td align="right">27</td>
<td align="right">44</td>
<td align="left">▅▅▇▁▁</td>
</tr>
</tbody>
</table>
</div>
<div id="skim-after-grouping-data" class="section level3">
<h3>Skim after grouping data</h3>
<p>We can use grouping and display the relevant information by group. Note below how pipe and group_by is used.</p>
<pre class="r"><code>mpg  %&gt;% group_by(drv) %&gt;%  skim(hwy)  </code></pre>
<table>
<caption>(#tab:select group)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">drv</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="left">drv</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">hwy</td>
<td align="left">4</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">19.17</td>
<td align="right">4.08</td>
<td align="right">12</td>
<td align="right">17</td>
<td align="right">18</td>
<td align="right">22</td>
<td align="right">28</td>
<td align="left">▃▇▅▁▅</td>
</tr>
<tr class="even">
<td align="left">hwy</td>
<td align="left">f</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">28.16</td>
<td align="right">4.21</td>
<td align="right">17</td>
<td align="right">26</td>
<td align="right">28</td>
<td align="right">29</td>
<td align="right">44</td>
<td align="left">▁▇▇▁▁</td>
</tr>
<tr class="odd">
<td align="left">hwy</td>
<td align="left">r</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">21.00</td>
<td align="right">3.66</td>
<td align="right">15</td>
<td align="right">17</td>
<td align="right">21</td>
<td align="right">24</td>
<td align="right">26</td>
<td align="left">▇▂▃▃▇</td>
</tr>
</tbody>
</table>
</div>
<div id="excluding-charts" class="section level3">
<h3>Excluding charts</h3>
<p>If you dont want the charts.You can use skim_without_charts.</p>
<pre class="r"><code>skim_without_charts(mpg) %&gt;% filter(skim_variable == &quot;hwy&quot;)</code></pre>
<table>
<caption>(#tab:select woc)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mpg</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.44</td>
<td align="right">5.95</td>
<td align="right">12</td>
<td align="right">18</td>
<td align="right">24</td>
<td align="right">27</td>
<td align="right">44</td>
</tr>
</tbody>
</table>
</div>
<div id="select-only-the-sections-we-want-to-see-using-yank" class="section level3">
<h3>Select only the sections we want to see using yank</h3>
<p>If we only want to see the numeric section we can yank that section.</p>
<pre class="r"><code>mpg %&gt;% skim() %&gt;% yank(&quot;numeric&quot;)</code></pre>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">displ</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3.47</td>
<td align="right">1.29</td>
<td align="right">1.6</td>
<td align="right">2.4</td>
<td align="right">3.3</td>
<td align="right">4.6</td>
<td align="right">7</td>
<td align="left">▇▆▆▃▁</td>
</tr>
<tr class="even">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2003.50</td>
<td align="right">4.51</td>
<td align="right">1999.0</td>
<td align="right">1999.0</td>
<td align="right">2003.5</td>
<td align="right">2008.0</td>
<td align="right">2008</td>
<td align="left">▇▁▁▁▇</td>
</tr>
<tr class="odd">
<td align="left">cyl</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.89</td>
<td align="right">1.61</td>
<td align="right">4.0</td>
<td align="right">4.0</td>
<td align="right">6.0</td>
<td align="right">8.0</td>
<td align="right">8</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="even">
<td align="left">cty</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">16.86</td>
<td align="right">4.26</td>
<td align="right">9.0</td>
<td align="right">14.0</td>
<td align="right">17.0</td>
<td align="right">19.0</td>
<td align="right">35</td>
<td align="left">▆▇▃▁▁</td>
</tr>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.44</td>
<td align="right">5.95</td>
<td align="right">12.0</td>
<td align="right">18.0</td>
<td align="right">24.0</td>
<td align="right">27.0</td>
<td align="right">44</td>
<td align="left">▅▅▇▁▁</td>
</tr>
</tbody>
</table>
</div>
<div id="specify-your-own-statistics-using-skim_with-and-sfl" class="section level3">
<h3>Specify your own statistics using skim_with and sfl</h3>
<p>Using skim_with we can specify our own statistics.For example we can make use of R’s stat package.
Note the default functionality is to append your statistics to the default output statistics that skim returns. By selecting append = FALSE we only return the statistics we specify.</p>
<pre class="r"><code>my_skim &lt;- skim_with(numeric = sfl(iqr = IQR, mad = mad, p99 = ~ quantile(., probs = .99)),
  append = FALSE)

my_skim(mpg,hwy)</code></pre>
<table>
<caption>(#tab:select myskim)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mpg</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">iqr</th>
<th align="right">mad</th>
<th align="right">p99</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">7.41</td>
<td align="right">39.68</td>
</tr>
</tbody>
</table>
<p>We can also exclude statistics we don’t want. Note below we set P25 and P75 to NULL. Note we didn’t specify append = FALSE so our addition of IQR gets appended to the default output.</p>
<pre class="r"><code>my_skim &lt;- skim_with(numeric = sfl(iqr = IQR, p25 = NULL, p75 = NULL))


my_skim(mpg,hwy)</code></pre>
<table>
<caption>(#tab:select myskimremove)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mpg</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">234</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p50</th>
<th align="right">p100</th>
<th align="left">hist</th>
<th align="right">iqr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">hwy</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.44</td>
<td align="right">5.95</td>
<td align="right">12</td>
<td align="right">24</td>
<td align="right">44</td>
<td align="left">▅▅▇▁▁</td>
<td align="right">9</td>
</tr>
</tbody>
</table>
</div>
<div id="keep-the-original-data-set-with-skim_tee" class="section level3">
<h3>Keep the original data set with skim_tee</h3>
<p>We can also use skim_tee() to return the original data after running skim</p>
<pre class="r"><code>mpg_tee &lt;- mpg %&gt;% skim_tee()  </code></pre>
<pre><code>## -- Data Summary ------------------------
##                            Values
## Name                       data  
## Number of rows             234   
## Number of columns          11    
## _______________________          
## Column type frequency:           
##   character                6     
##   numeric                  5     
## ________________________         
## Group variables            None  
## 
## -- Variable type: character ----------------------------------------------------
## # A tibble: 6 x 8
##   skim_variable n_missing complete_rate   min   max empty n_unique whitespace
## * &lt;chr&gt;             &lt;int&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;      &lt;int&gt;
## 1 manufacturer          0             1     4    10     0       15          0
## 2 model                 0             1     2    22     0       38          0
## 3 trans                 0             1     8    10     0       10          0
## 4 drv                   0             1     1     1     0        3          0
## 5 fl                    0             1     1     1     0        5          0
## 6 class                 0             1     3    10     0        7          0
## 
## -- Variable type: numeric ------------------------------------------------------
## # A tibble: 5 x 11
##   skim_variable n_missing complete_rate    mean    sd     p0    p25    p50
## * &lt;chr&gt;             &lt;int&gt;         &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 displ                 0             1    3.47  1.29    1.6    2.4    3.3
## 2 year                  0             1 2004.    4.51 1999   1999   2004. 
## 3 cyl                   0             1    5.89  1.61    4      4      6  
## 4 cty                   0             1   16.9   4.26    9     14     17  
## 5 hwy                   0             1   23.4   5.95   12     18     24  
##      p75  p100 hist 
## *  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
## 1    4.6     7 &lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2583&gt;&lt;U+2581&gt;
## 2 2008    2008 &lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;
## 3    8       8 &lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2587&gt;
## 4   19      35 &lt;U+2586&gt;&lt;U+2587&gt;&lt;U+2583&gt;&lt;U+2581&gt;&lt;U+2581&gt;
## 5   27      44 &lt;U+2585&gt;&lt;U+2585&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;</code></pre>
<pre class="r"><code>head(mpg_tee) </code></pre>
<pre><code>## # A tibble: 6 x 11
##   manufacturer model displ  year   cyl trans      drv     cty   hwy fl    class 
##   &lt;chr&gt;        &lt;chr&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 audi         a4      1.8  1999     4 auto(l5)   f        18    29 p     compa~
## 2 audi         a4      1.8  1999     4 manual(m5) f        21    29 p     compa~
## 3 audi         a4      2    2008     4 manual(m6) f        20    31 p     compa~
## 4 audi         a4      2    2008     4 auto(av)   f        21    30 p     compa~
## 5 audi         a4      2.8  1999     6 auto(l5)   f        16    26 p     compa~
## 6 audi         a4      2.8  1999     6 manual(m5) f        18    26 p     compa~</code></pre>
</div>
</div>
<div id="issues-encountered" class="section level2">
<h2>Issues encountered</h2>
<p>The one issue I encountered was with the spark lines. If you look at the skim_tee example the sparklines are
displayed as &lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2583&gt;&lt;U+2581&gt; for example.</p>
<p>Looking at <a href="https://cran.r-project.org/web/packages/skimr/readme/README.html" class="uri">https://cran.r-project.org/web/packages/skimr/readme/README.html</a> the reason given is as follows
" This longstanding problem originates in the low-level code for printing dataframes.</p>
<p>while skimr can render the histograms to the console and in RMarkdown documents, it cannot in other circumstances. This includes:</p>
<ul>
<li>converting a skimr data frame to a vanilla R data frame, but tibbles render correctly</li>
<li>in the context of rendering to a pdf using an engine that does not support utf-8."</li>
</ul>
<p>In these caes we can use the skim_without_charts as detailed above.</p>
<!--more-->
</div>
